import type { Metadata } from "next";
import { Outfit, Inter } from "next/font/google";
import "./globals.css";
import React from "react";
import {ThemeProvider} from "@/app/context/ThemeContext";

const outfit = Outfit({
  variable: "--font-outfit-var",
  subsets: ["latin"], weight:["400", "500", "600", "700"]
});

const inter = Inter({
  variable: "--font-inter-var",
  subsets: ["latin"], weight:["400"]
});

export const metadata: Metadata = {
  title: "Eurico Dande - Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={"scroll-smooth"}>
      <body
        className={`${outfit.variable} ${inter.variable} antialiased leading-8 overflow-x-hidden font-outfit dark:bg-dark-theme dark:text-white`}
      >
      <ThemeProvider>
        {children}
      </ThemeProvider>
      </body>
    </html>
  );
}
